Bump Jekyll to 4.3 for Ruby 3.3 compatibility
Jekyll 4.2.1 crashes on Ruby 3.3 due to changes in the standard
library's Logger module. The @level_override hash was removed,
causing "undefined method '[]' for nil" errors.

```
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/jekyll-4.2.1/lib/jekyll/log_adapter.rb:45:in `adjust_verbosity'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/jekyll-4.2.1/lib/jekyll/configuration.rb:143:in `config_files'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/jekyll-4.2.1/lib/jekyll.rb:118:in `configuration'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:44:in `configuration_from_options'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:83:in `block (2 levels) in init_with_program'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
```